#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
cookbook 'openoffice',
  :git => 'git://github.com/rgauss/chef-openoffice.git'
cookbook 'alfresco',
  :git => 'git://github.com/jasherai/chef-alfresco.git'
cookbook 'oracle-xe',
  :git => 'git://github.com/iamedu/chef-oracle-xe.git'
cookbook 'glassfish'
